//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardParameter
    {
        public long ID { get; set; }
        public Nullable<long> RoomId { get; set; }
        public long CompanyId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<byte> TurnsMeasureMethod { get; set; }
        public Nullable<int> TurnsMonthsOfUsageToSample { get; set; }
        public Nullable<int> AUDayOfUsageToSample { get; set; }
        public Nullable<byte> AUMeasureMethod { get; set; }
        public Nullable<int> AUDaysOfDailyUsage { get; set; }
        public Nullable<byte> MinMaxMeasureMethod { get; set; }
        public Nullable<int> MinMaxDayOfUsageToSample { get; set; }
        public Nullable<int> MinMaxDayOfAverage { get; set; }
        public Nullable<double> MinMaxMinNumberOfTimesMax { get; set; }
        public Nullable<int> MinMaxOptValue1 { get; set; }
        public Nullable<int> MinMaxOptValue2 { get; set; }
        public Nullable<int> GraphFromMonth { get; set; }
        public Nullable<int> GraphToMonth { get; set; }
        public Nullable<int> GraphFromYear { get; set; }
        public Nullable<int> GraphToYear { get; set; }
        public bool IsTrendingEnabled { get; set; }
        public Nullable<byte> PieChartmetricOn { get; set; }
        public Nullable<double> TurnsCalculatedStockRoomTurn { get; set; }
        public Nullable<double> AUCalculatedDailyUsageOverSample { get; set; }
        public Nullable<double> MinMaxCalculatedDailyUsageOverSample { get; set; }
        public Nullable<double> MinMaxCalcAvgPullByDay { get; set; }
        public Nullable<double> MinMaxCalcualtedMax { get; set; }
        public bool AutoClassification { get; set; }
        public Nullable<long> MonthlyAverageUsage { get; set; }
        public double AnnualCarryingCostPercent { get; set; }
        public double LargestAnnualCashSavings { get; set; }
        public Nullable<int> TurnsDaysOfUsageToSample { get; set; }
        public long EnterpriseID { get; set; }
    }
}
