//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardWidgetOrder
    {
        public long pk_WidgetOrder { get; set; }
        public long UserId { get; set; }
        public string WidgetOrder { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public long EnterpriseId { get; set; }
        public byte DashboardType { get; set; }
    }
}
