//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseMaster
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PostalCode { get; set; }
        public string Country { get; set; }
        public string ContactPhone { get; set; }
        public string ContactEmail { get; set; }
        public Nullable<double> SoftwareBasePrice { get; set; }
        public Nullable<double> MaxBinsPerBasePrice { get; set; }
        public Nullable<double> CostPerBin { get; set; }
        public Nullable<double> DiscountPrice1 { get; set; }
        public Nullable<double> DiscountPrice2 { get; set; }
        public Nullable<double> DiscountPrice3 { get; set; }
        public Nullable<int> MaxSubscriptionTier1 { get; set; }
        public Nullable<int> MaxSubscriptionTier2 { get; set; }
        public Nullable<int> MaxSubscriptionTier3 { get; set; }
        public Nullable<int> MaxSubscriptionTier4 { get; set; }
        public Nullable<int> MaxSubscriptionTier5 { get; set; }
        public Nullable<int> MaxSubscriptionTier6 { get; set; }
        public Nullable<double> PriceSubscriptionTier1 { get; set; }
        public Nullable<double> PriceSubscriptionTier2 { get; set; }
        public Nullable<double> PriceSubscriptionTier3 { get; set; }
        public Nullable<double> PriceSubscriptionTier4 { get; set; }
        public Nullable<double> PriceSubscriptionTier5 { get; set; }
        public Nullable<double> PriceSubscriptionTier6 { get; set; }
        public bool IncludeLicenseFees { get; set; }
        public Nullable<int> MaxLicenseTier1 { get; set; }
        public Nullable<int> MaxLicenseTier2 { get; set; }
        public Nullable<int> MaxLicenseTier3 { get; set; }
        public Nullable<int> MaxLicenseTier4 { get; set; }
        public Nullable<int> MaxLicenseTier5 { get; set; }
        public Nullable<int> MaxLicenseTier6 { get; set; }
        public Nullable<double> PriceLicenseTier1 { get; set; }
        public Nullable<double> PriceLicenseTier2 { get; set; }
        public Nullable<double> PriceLicenseTier3 { get; set; }
        public Nullable<double> PriceLicenseTier4 { get; set; }
        public Nullable<double> PriceLicenseTier5 { get; set; }
        public Nullable<double> PriceLicenseTier6 { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string EnterpriseDBName { get; set; }
        public string EnterpriseDBConnectionString { get; set; }
        public string EnterPriseLogo { get; set; }
        public string EnterpriseSqlServerName { get; set; }
        public string EnterpriseSqlServerUserName { get; set; }
        public string EnterpriseSqlServerPassword { get; set; }
        public bool IsActive { get; set; }
        public Nullable<long> EnterpriseSuperAdmin { get; set; }
        public string EnterpriseDomainURL { get; set; }
        public string HistoryDBName { get; set; }
        public string ChangeLogDbName { get; set; }
        public string ArchiveDbName { get; set; }
        public bool AllowABIntegration { get; set; }
        public bool IsCreatedFromNLF { get; set; }
    }
}
