//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseScriptsMaster
    {
        public long SQLScriptID { get; set; }
        public string ScriptName { get; set; }
        public string ScriptText { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public int ExecuitionSequence { get; set; }
        public bool IsMasterScript { get; set; }
        public bool IsSQLCEScriptTemplate { get; set; }
        public string Version { get; set; }
    }
}
