//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseSqlScriptsDetail
    {
        public long EnterpriseSqlScriptsDtlID { get; set; }
        public long SQLScriptID { get; set; }
        public long EnterpriseID { get; set; }
        public bool IsExecuitedSuccessfully { get; set; }
        public bool IsLatestExecution { get; set; }
        public string ReturnResult { get; set; }
    }
}
