//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterpriseDomain
    {
        public long ID { get; set; }
        public long EnterpriseID { get; set; }
        public string DomainName { get; set; }
        public string DomainURL { get; set; }
        public string RedirectDomainURL { get; set; }
        public string EpUniqueKey { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsSecureOnly { get; set; }
    }
}
