//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTurns_MasterEntities : DbContext
    {
        public eTurns_MasterEntities()
            : base("name=eTurns_MasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DashboardParameter> DashboardParameters { get; set; }
        public virtual DbSet<DashboardWidgetOrder> DashboardWidgetOrders { get; set; }
        public virtual DbSet<eMailAttachment> eMailAttachments { get; set; }
        public virtual DbSet<eMailToSend> eMailToSends { get; set; }
        public virtual DbSet<EnterPriseConfig> EnterPriseConfigs { get; set; }
        public virtual DbSet<EnterpriseDomain> EnterpriseDomains { get; set; }
        public virtual DbSet<EnterpriseMaster> EnterpriseMasters { get; set; }
        public virtual DbSet<EnterpriseScriptsMaster> EnterpriseScriptsMasters { get; set; }
        public virtual DbSet<EnterpriseSqlScriptsDetail> EnterpriseSqlScriptsDetails { get; set; }
        public virtual DbSet<EulaMaster> EulaMasters { get; set; }
        public virtual DbSet<ForgotPasswordRequest> ForgotPasswordRequests { get; set; }
        public virtual DbSet<HelpDocumentMaster> HelpDocumentMasters { get; set; }
        public virtual DbSet<MobileResource> MobileResources { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<MstCompanyMaster> MstCompanyMasters { get; set; }
        public virtual DbSet<ParentModuleMaster> ParentModuleMasters { get; set; }
        public virtual DbSet<ReportSchedulerError> ReportSchedulerErrors { get; set; }
        public virtual DbSet<ResourceLaguage> ResourceLaguages { get; set; }
        public virtual DbSet<ResourceModuleDetails_Mobile> ResourceModuleDetails_Mobile { get; set; }
        public virtual DbSet<ResourceModuleMaster> ResourceModuleMasters { get; set; }
        public virtual DbSet<RoleCompanyDetail> RoleCompanyDetails { get; set; }
        public virtual DbSet<RoleEnterpriseDetail> RoleEnterpriseDetails { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RoleModuleDetail> RoleModuleDetails { get; set; }
        public virtual DbSet<RoleRoomAccess> RoleRoomAccesses { get; set; }
        public virtual DbSet<RoleRoomsDetail> RoleRoomsDetails { get; set; }
        public virtual DbSet<RoomReferencesDeleteScheduleDetail> RoomReferencesDeleteScheduleDetails { get; set; }
        public virtual DbSet<SchedulerErrorLog> SchedulerErrorLogs { get; set; }
        public virtual DbSet<UDF> UDFs { get; set; }
        public virtual DbSet<UDFOption> UDFOptions { get; set; }
        public virtual DbSet<UserLicenceAccept> UserLicenceAccepts { get; set; }
        public virtual DbSet<UserLoginFailAttempt> UserLoginFailAttempts { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserMaster_History> UserMaster_History { get; set; }
        public virtual DbSet<UserPasswordChangeHistory> UserPasswordChangeHistories { get; set; }
        public virtual DbSet<UserRoleDetail> UserRoleDetails { get; set; }
        public virtual DbSet<UserRoomAccess> UserRoomAccesses { get; set; }
        public virtual DbSet<UserRoomsDetail> UserRoomsDetails { get; set; }
        public virtual DbSet<UsersUISetting> UsersUISettings { get; set; }
        public virtual DbSet<UserTypeMaster> UserTypeMasters { get; set; }
        public virtual DbSet<ECRChangesQueue> ECRChangesQueues { get; set; }
        public virtual DbSet<UsersUISettingsNG> UsersUISettingsNGs { get; set; }
        public virtual DbSet<MstRoom> MstRooms { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
    }
}
