//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ForgotPasswordRequest
    {
        public long ID { get; set; }
        public long UserId { get; set; }
        public System.Guid RequestToken { get; set; }
        public System.DateTime TokenGeneratedDate { get; set; }
        public bool IsProcessed { get; set; }
        public bool IsExpired { get; set; }
    }
}
