//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class HelpDocumentMaster
    {
        public long ID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleDocName { get; set; }
        public string ModuleDocPath { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public string ModuleVideoPath { get; set; }
        public Nullable<bool> IsDoc { get; set; }
        public Nullable<bool> IsVideo { get; set; }
        public string ModuleVideoName { get; set; }
        public Nullable<int> DocType { get; set; }
    }
}
