//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MobileResource
    {
        public long ID { get; set; }
        public long ResourcePageID { get; set; }
        public string ResourceKey { get; set; }
        public string ResourceValue { get; set; }
        public long LanguageID { get; set; }
        public long CompanyID { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
