//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceModuleDetails_Mobile
    {
        public long ID { get; set; }
        public string PageName { get; set; }
        public string DisplayPageName { get; set; }
        public Nullable<long> ResourceModuleID { get; set; }
        public string ResMobModuleDetailsKey { get; set; }
    }
}
