//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceLaguage
    {
        public long ID { get; set; }
        public string Language { get; set; }
        public string Culture { get; set; }
    }
}
