//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleEnterpriseDetail
    {
        public long ID { get; set; }
        public long EnterpriseId { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public bool IsDeleted { get; set; }
        public long RoleId { get; set; }
    }
}
