//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomReferencesDeleteScheduleDetail
    {
        public long Id { get; set; }
        public string RoomIds { get; set; }
        public string EnterpriseDBName { get; set; }
        public Nullable<long> EnterpriseId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<int> ProcessStatus { get; set; }
    }
}
