//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchedulerErrorLog
    {
        public long ID { get; set; }
        public long SchedulerID { get; set; }
        public string ExceptionDetails { get; set; }
        public string MailSentTo { get; set; }
        public int ScheduleFor { get; set; }
        public long RoomID { get; set; }
        public long CompanyID { get; set; }
        public long EnterpriseID { get; set; }
        public System.DateTime Created { get; set; }
    }
}
