//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoleDetail
    {
        public long ID { get; set; }
        public long RoleID { get; set; }
        public long UserID { get; set; }
        public long ModuleID { get; set; }
        public bool IsInsert { get; set; }
        public bool IsDelete { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsView { get; set; }
        public string ModuleValue { get; set; }
        public bool IsChecked { get; set; }
        public System.Guid GUID { get; set; }
        public bool ShowDeleted { get; set; }
        public bool ShowArchived { get; set; }
        public bool ShowUDF { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public long EnterpriseId { get; set; }
        public bool ShowChangeLog { get; set; }
    }
}
