//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMaster_History
    {
        public long HistoryId { get; set; }
        public string Action { get; set; }
        public long ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public long RoleId { get; set; }
        public Nullable<double> SyncMins { get; set; }
        public Nullable<System.TimeSpan> SyncDailyTime { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid GUID { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<long> RoomId { get; set; }
        public long CompanyID { get; set; }
        public long EnterpriseId { get; set; }
        public bool IsEnterPriseUser { get; set; }
        public Nullable<int> UserType { get; set; }
        public bool IsLicenceAccepted { get; set; }
        public bool IsLocked { get; set; }
        public Nullable<System.DateTime> LastSyncDateTime { get; set; }
        public string PDABuildVersion { get; set; }
        public Nullable<bool> IsRequistionReportDisplay { get; set; }
        public Nullable<bool> IseTurnsAdmin { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public string Prefix { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Gender { get; set; }
        public string Phone2 { get; set; }
        public string EmployeeNumber { get; set; }
        public string CostCenter { get; set; }
        public string JobTitle { get; set; }
        public string Address { get; set; }
        public string Country { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string PostalCode { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public bool IsNgNLFAllowed { get; set; }
        public bool EnforceRolePermission { get; set; }
    }
}
