//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPasswordChangeHistory
    {
        public long Id { get; set; }
        public long UserId { get; set; }
        public string OldPassword { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public Nullable<bool> IsCheked { get; set; }
    }
}
