//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurnsMaster.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public long Id { get; set; }
        public Nullable<long> UserId { get; set; }
        public Nullable<bool> IsRemember { get; set; }
        public string RedirectURL { get; set; }
        public Nullable<bool> IsRequistionReportDisplay { get; set; }
        public bool IsNeverExpirePwd { get; set; }
        public bool ShowDateTime { get; set; }
        public bool IsAutoLogin { get; set; }
        public int SearchPattern { get; set; }
        public bool ShowABConsentRemider { get; set; }
    }
}
