//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssetMaster
    {
        public long ID { get; set; }
        public string AssetName { get; set; }
        public string Description { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Serial { get; set; }
        public Nullable<long> ToolCategoryID { get; set; }
        public Nullable<System.DateTime> PurchaseDate { get; set; }
        public Nullable<double> PurchasePrice { get; set; }
        public Nullable<double> DepreciatedValue { get; set; }
        public Nullable<System.DateTime> SuggestedMaintenanceDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<byte> MaintenanceCount { get; set; }
        public Nullable<long> AssetCategoryId { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public bool IsAutoMaintain { get; set; }
        public Nullable<int> NoOfPastMntsToConsider { get; set; }
        public int MaintenanceType { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string AssetImageExternalURL { get; set; }
        public string ImagePath { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> MaintenanceDueNoticeDays { get; set; }
    
        public virtual AssetCategoryMaster AssetCategoryMaster { get; set; }
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual ToolCategoryMaster ToolCategoryMaster { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
