//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AutoSequenceNumber
    {
        public long ID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string Prefix { get; set; }
        public Nullable<long> RangeStartFrom { get; set; }
        public Nullable<int> Increment { get; set; }
        public Nullable<long> LastGenereted { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
    }
}
