//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BarcodeMaster
    {
        public long ID { get; set; }
        public System.Guid ModuleGuid { get; set; }
        public System.Guid RefGuid { get; set; }
        public string BarcodeString { get; set; }
        public long RoomID { get; set; }
        public long CompanyID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string BarcodeAdded { get; set; }
        public Nullable<System.Guid> BinGuid { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public Nullable<System.DateTime> ReceivedOnWeb { get; set; }
    }
}
