//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BinMaster()
        {
            this.InventoryCountDetails = new HashSet<InventoryCountDetail>();
            this.ItemLocationDetails = new HashSet<ItemLocationDetail>();
            this.ItemLocationeVMISetups = new HashSet<ItemLocationeVMISetup>();
            this.KitMoveInOutDetails = new HashSet<KitMoveInOutDetail>();
            this.MaterialStagings = new HashSet<MaterialStaging>();
            this.MaterialStagingDetails = new HashSet<MaterialStagingDetail>();
            this.MaterialStagingPullDetails = new HashSet<MaterialStagingPullDetail>();
            this.MaterialStagingPullDetails1 = new HashSet<MaterialStagingPullDetail>();
            this.PullDetails = new HashSet<PullDetail>();
            this.PullMasters = new HashSet<PullMaster>();
            this.ReceivedOrderTransferDetails = new HashSet<ReceivedOrderTransferDetail>();
            this.RequisitionDetails = new HashSet<RequisitionDetail>();
            this.TransferInOutItemDetails = new HashSet<TransferInOutItemDetail>();
            this.TransferInOutQtyDetails = new HashSet<TransferInOutQtyDetail>();
            this.WorkOrderLineItems = new HashSet<WorkOrderLineItem>();
        }
    
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string BinNumber { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public bool IsStagingLocation { get; set; }
        public bool IsStagingHeader { get; set; }
        public Nullable<System.Guid> MaterialStagingGUID { get; set; }
        public Nullable<double> CriticalQuantity { get; set; }
        public Nullable<double> MinimumQuantity { get; set; }
        public Nullable<double> MaximumQuantity { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<double> SuggestedOrderQuantity { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<long> ParentBinId { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<bool> IsEnforceDefaultPullQuantity { get; set; }
        public Nullable<bool> IsEnforceDefaultReorderQuantity { get; set; }
        public Nullable<double> DefaultPullQuantity { get; set; }
        public Nullable<double> DefaultReorderQuantity { get; set; }
        public string BinUDF1 { get; set; }
        public string BinUDF2 { get; set; }
        public string BinUDF3 { get; set; }
        public string BinUDF4 { get; set; }
        public string BinUDF5 { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventoryCountDetail> InventoryCountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLocationDetail> ItemLocationDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemLocationeVMISetup> ItemLocationeVMISetups { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KitMoveInOutDetail> KitMoveInOutDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStaging> MaterialStagings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStagingDetail> MaterialStagingDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStagingPullDetail> MaterialStagingPullDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialStagingPullDetail> MaterialStagingPullDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PullDetail> PullDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PullMaster> PullMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReceivedOrderTransferDetail> ReceivedOrderTransferDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RequisitionDetail> RequisitionDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferInOutItemDetail> TransferInOutItemDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferInOutQtyDetail> TransferInOutQtyDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderLineItem> WorkOrderLineItems { get; set; }
    }
}
