//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class BinMaster_History
    {
        public long HistoryID { get; set; }
        public string Action { get; set; }
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string BinNumber { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public Nullable<bool> IsStagingLocation { get; set; }
        public bool IsStagingHeader { get; set; }
        public Nullable<System.Guid> MaterialStagingGUID { get; set; }
        public Nullable<double> CriticalQuantity { get; set; }
        public Nullable<double> MinimumQuantity { get; set; }
        public Nullable<double> MaximumQuantity { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<double> SuggestedOrderQuantity { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public Nullable<long> ParentBinId { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
    }
}
