//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CartItem_History
    {
        public long HistoryId { get; set; }
        public long ID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public string Status { get; set; }
        public string ReplenishType { get; set; }
        public Nullable<bool> IsKitComponent { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public string Action { get; set; }
        public bool IsAutoMatedEntry { get; set; }
        public Nullable<System.Guid> BinGUID { get; set; }
        public Nullable<long> BinId { get; set; }
        public Nullable<System.Guid> RefOrderTransferGUID { get; set; }
        public bool IsOrderTransferMade { get; set; }
        public Nullable<long> RefOrderTransferId { get; set; }
        public string WhatWhereAction { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public System.DateTime HistoryCreatedOn { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
    }
}
