//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogReportDetail
    {
        public long ID { get; set; }
        public string Name { get; set; }
        public long TemplateID { get; set; }
        public string SelectedFields { get; set; }
        public bool IncludeBin { get; set; }
        public bool IncludeQuantity { get; set; }
        public string QuantityField { get; set; }
        public string BarcodeKey { get; set; }
        public string LabelHTML { get; set; }
        public string LabelXML { get; set; }
        public Nullable<double> FontSize { get; set; }
        public string TextFont { get; set; }
        public string BarcodeFont { get; set; }
        public string BarcodePattern { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public long RoomID { get; set; }
        public long CompanyID { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    }
}
