//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountLineItemDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<long> BinID { get; set; }
        public Nullable<double> CustomerOwnedQuantity { get; set; }
        public Nullable<double> CountCustomerOwnedQuantity { get; set; }
        public Nullable<double> ConsignedQuantity { get; set; }
        public Nullable<double> CountConsignedQuantity { get; set; }
        public string LotNumber { get; set; }
        public string SerialNumber { get; set; }
        public string Comment { get; set; }
        public string Expiration { get; set; }
        public string Received { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<double> Cost { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<System.Guid> CountGUID { get; set; }
        public Nullable<System.Guid> CountDetailGUID { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<double> ConsignedDifference { get; set; }
        public Nullable<double> CusOwnedDifference { get; set; }
    }
}
