//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CreditHistory
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid PullDetailGuid { get; set; }
        public System.Guid PULLGUID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public Nullable<double> CreditCustomerOwnedQuantity { get; set; }
        public Nullable<double> CreditConsignedQuantity { get; set; }
        public long CompanyID { get; set; }
        public long Room { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<System.Guid> CreditGuid { get; set; }
        public Nullable<System.Guid> CreditDetailGuid { get; set; }
    }
}
