//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CycleCountSetting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CycleCountSetting()
        {
            this.CycleCountSetUps = new HashSet<CycleCountSetUp>();
        }
    
        public int ID { get; set; }
        public short AClassFrequency { get; set; }
        public short BClassFrequency { get; set; }
        public short CClassFrequency { get; set; }
        public short DClassFrequency { get; set; }
        public short EClassFrequency { get; set; }
        public System.DateTime YearStartDate { get; set; }
        public string EmailAddressesPreCountNotification { get; set; }
        public string EmailAddressesDailyCycle { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public System.Guid GUID { get; set; }
        public long CompanyId { get; set; }
        public long RoomId { get; set; }
        public bool IsActive { get; set; }
        public short FClassFrequency { get; set; }
        public Nullable<System.DateTime> YearEndDate { get; set; }
        public int RecurrringDays { get; set; }
        public System.TimeSpan CycleCountTime { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public int CountFrequencyType { get; set; }
        public int CycleCountsPerCycle { get; set; }
        public int RecurringType { get; set; }
        public System.TimeSpan MissedItemsEmailTime { get; set; }
        public int MissedItemEmailPriorHours { get; set; }
        public string CountType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CycleCountSetUp> CycleCountSetUps { get; set; }
    }
}
