//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DashboardCalculation
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<int> Month { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<decimal> OnHandQty { get; set; }
        public Nullable<decimal> InventoryValue { get; set; }
        public Nullable<decimal> CalculateCost { get; set; }
        public Nullable<decimal> PulledQty { get; set; }
        public Nullable<decimal> OrderQty { get; set; }
        public Nullable<decimal> MonthlyTotalPulled { get; set; }
        public Nullable<decimal> TurnsPullQty { get; set; }
        public Nullable<decimal> AnnualTurnsPullQty { get; set; }
        public Nullable<decimal> TurnsOrderQty { get; set; }
        public Nullable<decimal> AnnualTurnsOrderQty { get; set; }
        public Nullable<decimal> PulledUsage { get; set; }
        public Nullable<decimal> MonthlyPulledQty { get; set; }
        public Nullable<decimal> MonthlyOrderQty { get; set; }
        public Nullable<decimal> TurnsAmt { get; set; }
        public Nullable<decimal> AnnualTurnAmt { get; set; }
    }
}
