//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefaultItemValue
    {
        public long ID { get; set; }
        public Nullable<double> DefaultReorderQuantity { get; set; }
        public Nullable<double> DefaultPullQuantity { get; set; }
        public Nullable<bool> Trend { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<bool> Consignment { get; set; }
        public Nullable<double> CriticalQuantity { get; set; }
        public Nullable<double> MinimumQuantity { get; set; }
        public Nullable<double> MaximumQuantity { get; set; }
        public Nullable<bool> SerialNumberTracking { get; set; }
        public Nullable<bool> LotNumberTracking { get; set; }
        public Nullable<bool> DateCodeTracking { get; set; }
        public Nullable<int> ItemType { get; set; }
        public Nullable<bool> IsBOMItem { get; set; }
        public Nullable<bool> PullQtyScanOverride { get; set; }
        public Nullable<bool> IsAutoInventoryClassification { get; set; }
        public Nullable<bool> IsPackslipMandatoryAtReceive { get; set; }
        public Nullable<double> LastCost { get; set; }
        public Nullable<System.DateTime> ReceivedOnWeb { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<double> OutTransferQuantity { get; set; }
        public Nullable<long> UOMID { get; set; }
        public Nullable<long> CostUOMID { get; set; }
        public Nullable<bool> IsItemLevelMinMaxQtyRequired { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<bool> IsConsignedSerialLot { get; set; }
        public Nullable<bool> IsWebEdit { get; set; }
        public Nullable<bool> IsPDAEdit { get; set; }
        public Nullable<long> BinID { get; set; }
        public string ItemUniqueNumber { get; set; }
    }
}
