//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailUserMasterDetail
    {
        public long ID { get; set; }
        public string TemplateName { get; set; }
        public Nullable<long> EmailUserID { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CompanyId { get; set; }
    
        public virtual EmailUserMaster EmailUserMaster { get; set; }
    }
}
