//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eMailToSend
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public eMailToSend()
        {
            this.eMailAttachments = new HashSet<eMailAttachment>();
        }
    
        public long ID { get; set; }
        public string ToAddress { get; set; }
        public string CCAddress { get; set; }
        public string BCCAddress { get; set; }
        public string Subject { get; set; }
        public string MailBody { get; set; }
        public Nullable<long> EnterpriseID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<bool> HasAttachment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> SendingTried { get; set; }
        public string FromEmailId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<eMailAttachment> eMailAttachments { get; set; }
    }
}
