//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eMailAttachment
    {
        public long ID { get; set; }
        public long EmailToSendID { get; set; }
        public string MimeType { get; set; }
        public string AttachedFileName { get; set; }
        public byte[] FileData { get; set; }
    
        public virtual eMailToSend eMailToSend { get; set; }
    }
}
