//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailTemplateDetail
    {
        public long ID { get; set; }
        public long EmailTemplateId { get; set; }
        public string MailBodyText { get; set; }
        public long ResourceLaguageId { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public long CompanyID { get; set; }
        public long RoomId { get; set; }
        public string MailSubject { get; set; }
        public Nullable<long> NotificationID { get; set; }
        public Nullable<long> ReportId { get; set; }
    
        public virtual EmailTemplate EmailTemplate { get; set; }
        public virtual ResourceLaguage ResourceLaguage { get; set; }
    }
}
