//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailUserMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EmailUserMaster()
        {
            this.EmailUserMasterDetails = new HashSet<EmailUserMasterDetail>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Email { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EmailUserMasterDetail> EmailUserMasterDetails { get; set; }
    }
}
