//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnterPriseConfig
    {
        public long ID { get; set; }
        public Nullable<long> EnterpriseID { get; set; }
        public Nullable<int> ScheduleDaysBefore { get; set; }
        public Nullable<double> OperationalHoursBefore { get; set; }
        public Nullable<double> MileageBefore { get; set; }
        public Nullable<int> ProjectAmountExceed { get; set; }
        public Nullable<int> ProjectItemQuantitExceed { get; set; }
        public Nullable<int> ProjectItemAmountExceed { get; set; }
        public Nullable<int> CostDecimalPoints { get; set; }
        public Nullable<int> QuantityDecimalPoints { get; set; }
        public string DateFormat { get; set; }
        public Nullable<int> NOBackDays { get; set; }
        public Nullable<int> NODaysAve { get; set; }
        public Nullable<decimal> NOTimes { get; set; }
        public Nullable<int> MinPer { get; set; }
        public Nullable<int> MaxPer { get; set; }
        public string CurrencySymbol { get; set; }
        public string AEMTPndOrders { get; set; }
        public string AEMTPndRequisition { get; set; }
        public string AEMTPndTransfer { get; set; }
        public string AEMTSggstOrdMin { get; set; }
        public string AEMTSggstOrdCrt { get; set; }
        public string AEMTAssetMntDue { get; set; }
        public string AEMTToolsMntDue { get; set; }
        public string AEMTItemStockOut { get; set; }
        public string AEMTCycleCount { get; set; }
        public string AEMTCycleCntItmMiss { get; set; }
        public string AEMTItemUsageRpt { get; set; }
        public string AEMTItemReceiveRpt { get; set; }
        public Nullable<int> GridRefreshTimeInSecond { get; set; }
        public string DateFormatCSharp { get; set; }
        public Nullable<int> PasswordExpiryDays { get; set; }
        public Nullable<int> NumberOfBackDaysToSyncOverPDA { get; set; }
        public Nullable<int> PasswordExpiryWarningDays { get; set; }
        public Nullable<int> PreviousLastAllowedPWD { get; set; }
        public Nullable<int> DisplayAgreePopupDays { get; set; }
        public string NotAllowedCharacter { get; set; }
    }
}
