//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTurnsMasterEntities : DbContext
    {
        public eTurnsMasterEntities()
            : base("name=eTurnsMasterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<eMailAttachment> eMailAttachments { get; set; }
        public virtual DbSet<eMailToSend> eMailToSends { get; set; }
        public virtual DbSet<MstCompanyMaster> MstCompanyMasters { get; set; }
        public virtual DbSet<MstRoom> MstRooms { get; set; }
    }
}
