//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eTurnsEntities : DbContext
    {
        public eTurnsEntities()
            : base("name=eTurnsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ArchiveSchedule> ArchiveSchedules { get; set; }
        public virtual DbSet<AssetCategoryMaster> AssetCategoryMasters { get; set; }
        public virtual DbSet<AssetMaster> AssetMasters { get; set; }
        public virtual DbSet<AutoSequenceNumber> AutoSequenceNumbers { get; set; }
        public virtual DbSet<BarcodeMaster> BarcodeMasters { get; set; }
        public virtual DbSet<CartItem> CartItems { get; set; }
        public virtual DbSet<CatalogReportDetail> CatalogReportDetails { get; set; }
        public virtual DbSet<CatalogReportTemplateMaster> CatalogReportTemplateMasters { get; set; }
        public virtual DbSet<CategoryMaster> CategoryMasters { get; set; }
        public virtual DbSet<CompanyConfig> CompanyConfigs { get; set; }
        public virtual DbSet<CompanyMaster> CompanyMasters { get; set; }
        public virtual DbSet<CostUOMMaster> CostUOMMasters { get; set; }
        public virtual DbSet<CountLineItemDetail> CountLineItemDetails { get; set; }
        public virtual DbSet<CountryMaster> CountryMasters { get; set; }
        public virtual DbSet<CreditHistory> CreditHistories { get; set; }
        public virtual DbSet<CustomerMaster> CustomerMasters { get; set; }
        public virtual DbSet<CycleCountSetting> CycleCountSettings { get; set; }
        public virtual DbSet<CycleCountSetUp> CycleCountSetUps { get; set; }
        public virtual DbSet<DashboardCalculation> DashboardCalculations { get; set; }
        public virtual DbSet<DashboardWidgetOrder> DashboardWidgetOrders { get; set; }
        public virtual DbSet<DefaultItemValue> DefaultItemValues { get; set; }
        public virtual DbSet<EmailTemplate> EmailTemplates { get; set; }
        public virtual DbSet<EmailTemplateDetail> EmailTemplateDetails { get; set; }
        public virtual DbSet<EmailTokenDetail> EmailTokenDetails { get; set; }
        public virtual DbSet<EmailTokenMaster> EmailTokenMasters { get; set; }
        public virtual DbSet<EmailUserMaster> EmailUserMasters { get; set; }
        public virtual DbSet<EmailUserMasterDetail> EmailUserMasterDetails { get; set; }
        public virtual DbSet<EnterPriseConfig> EnterPriseConfigs { get; set; }
        public virtual DbSet<EnterpriseMaster> EnterpriseMasters { get; set; }
        public virtual DbSet<eVMIPollHistory> eVMIPollHistories { get; set; }
        public virtual DbSet<FreightTypeMaster> FreightTypeMasters { get; set; }
        public virtual DbSet<FTPMaster> FTPMasters { get; set; }
        public virtual DbSet<GLAccountMaster> GLAccountMasters { get; set; }
        public virtual DbSet<GlobalUISetting> GlobalUISettings { get; set; }
        public virtual DbSet<GXPRConsigmentJobMaster> GXPRConsigmentJobMasters { get; set; }
        public virtual DbSet<HelpDocumentMaster> HelpDocumentMasters { get; set; }
        public virtual DbSet<InventoryAnalysisMonthWise> InventoryAnalysisMonthWises { get; set; }
        public virtual DbSet<InventoryClassificationMaster> InventoryClassificationMasters { get; set; }
        public virtual DbSet<InventoryCount> InventoryCounts { get; set; }
        public virtual DbSet<InventoryCount_History> InventoryCount_History { get; set; }
        public virtual DbSet<InventoryCountCycle> InventoryCountCycles { get; set; }
        public virtual DbSet<InventoryCountDetail> InventoryCountDetails { get; set; }
        public virtual DbSet<InventoryCountDetail_History> InventoryCountDetail_History { get; set; }
        public virtual DbSet<ItemLocationeVMISetup> ItemLocationeVMISetups { get; set; }
        public virtual DbSet<ItemLocationQTY> ItemLocationQTies { get; set; }
        public virtual DbSet<ItemManufacturerDetail> ItemManufacturerDetails { get; set; }
        public virtual DbSet<ItemStockOutHistory> ItemStockOutHistories { get; set; }
        public virtual DbSet<ItemStockOutMailLog> ItemStockOutMailLogs { get; set; }
        public virtual DbSet<ItemSupplierDetail> ItemSupplierDetails { get; set; }
        public virtual DbSet<JobTypeMaster> JobTypeMasters { get; set; }
        public virtual DbSet<KitDetail> KitDetails { get; set; }
        public virtual DbSet<KitMaster> KitMasters { get; set; }
        public virtual DbSet<KitMoveInOutDetail> KitMoveInOutDetails { get; set; }
        public virtual DbSet<LabelFieldModuleTemplateDetail> LabelFieldModuleTemplateDetails { get; set; }
        public virtual DbSet<LabelModuleFieldMaster> LabelModuleFieldMasters { get; set; }
        public virtual DbSet<LabelModuleMaster> LabelModuleMasters { get; set; }
        public virtual DbSet<LabelModuleTemplateDetail> LabelModuleTemplateDetails { get; set; }
        public virtual DbSet<LabelTemplateMaster> LabelTemplateMasters { get; set; }
        public virtual DbSet<LocationMaster> LocationMasters { get; set; }
        public virtual DbSet<ManufacturerMaster> ManufacturerMasters { get; set; }
        public virtual DbSet<MaterialStaging> MaterialStagings { get; set; }
        public virtual DbSet<MaterialStagingDetail> MaterialStagingDetails { get; set; }
        public virtual DbSet<MaterialStagingPullDetail> MaterialStagingPullDetails { get; set; }
        public virtual DbSet<MeasurementTermMaster> MeasurementTermMasters { get; set; }
        public virtual DbSet<MobileResource> MobileResources { get; set; }
        public virtual DbSet<ModuleMaster> ModuleMasters { get; set; }
        public virtual DbSet<ModuleNotification> ModuleNotifications { get; set; }
        public virtual DbSet<ModuleWiseReportForDefaultPrint> ModuleWiseReportForDefaultPrints { get; set; }
        public virtual DbSet<MoveMaterialDetail> MoveMaterialDetails { get; set; }
        public virtual DbSet<MoveMaterialMaster> MoveMaterialMasters { get; set; }
        public virtual DbSet<Notification> Notifications { get; set; }
        public virtual DbSet<OrderDetail> OrderDetails { get; set; }
        public virtual DbSet<OrderUOMMaster> OrderUOMMasters { get; set; }
        public virtual DbSet<ParentModuleMaster> ParentModuleMasters { get; set; }
        public virtual DbSet<PDAEmailsToSend> PDAEmailsToSends { get; set; }
        public virtual DbSet<PDAGridColumnList> PDAGridColumnLists { get; set; }
        public virtual DbSet<PDASearchSetting> PDASearchSettings { get; set; }
        public virtual DbSet<PermissionTemplateDetail> PermissionTemplateDetails { get; set; }
        public virtual DbSet<PermissionTemplateMaster> PermissionTemplateMasters { get; set; }
        public virtual DbSet<PollAllFlagMaster> PollAllFlagMasters { get; set; }
        public virtual DbSet<PollAllHistory> PollAllHistories { get; set; }
        public virtual DbSet<PreReceivOrderDetail> PreReceivOrderDetails { get; set; }
        public virtual DbSet<PreReceivOrderToolDetail> PreReceivOrderToolDetails { get; set; }
        public virtual DbSet<ProjectMaster> ProjectMasters { get; set; }
        public virtual DbSet<ProjectSpendItem> ProjectSpendItems { get; set; }
        public virtual DbSet<PullDetail> PullDetails { get; set; }
        public virtual DbSet<PullEditHistory> PullEditHistories { get; set; }
        public virtual DbSet<PullPOMaster> PullPOMasters { get; set; }
        public virtual DbSet<QuickListItem> QuickListItems { get; set; }
        public virtual DbSet<QuickListMaster> QuickListMasters { get; set; }
        public virtual DbSet<ReceivedToolAssetOrderTransferDetail> ReceivedToolAssetOrderTransferDetails { get; set; }
        public virtual DbSet<ReceiveOrderDetail> ReceiveOrderDetails { get; set; }
        public virtual DbSet<ReceiveTransferDetail> ReceiveTransferDetails { get; set; }
        public virtual DbSet<RegionalSetting> RegionalSettings { get; set; }
        public virtual DbSet<ReportGroupMaster> ReportGroupMasters { get; set; }
        public virtual DbSet<ReportMailLog> ReportMailLogs { get; set; }
        public virtual DbSet<RequisitionDetail> RequisitionDetails { get; set; }
        public virtual DbSet<ResourceFileLink> ResourceFileLinks { get; set; }
        public virtual DbSet<ResourceLaguage> ResourceLaguages { get; set; }
        public virtual DbSet<ResourceModuleDetail> ResourceModuleDetails { get; set; }
        public virtual DbSet<ResourceModuleDetails_Mobile> ResourceModuleDetails_Mobile { get; set; }
        public virtual DbSet<ResourceModuleMaster> ResourceModuleMasters { get; set; }
        public virtual DbSet<RoleMaster> RoleMasters { get; set; }
        public virtual DbSet<RoleModuleDetail> RoleModuleDetails { get; set; }
        public virtual DbSet<RoleRoomAccess> RoleRoomAccesses { get; set; }
        public virtual DbSet<RoleRoomsDetail> RoleRoomsDetails { get; set; }
        public virtual DbSet<RoomModuleSetting> RoomModuleSettings { get; set; }
        public virtual DbSet<RoomSchedule> RoomSchedules { get; set; }
        public virtual DbSet<RoomScheduleDetail> RoomScheduleDetails { get; set; }
        public virtual DbSet<ScriptsExecution> ScriptsExecutions { get; set; }
        public virtual DbSet<ShipViaMaster> ShipViaMasters { get; set; }
        public virtual DbSet<SiteListColumnDetail> SiteListColumnDetails { get; set; }
        public virtual DbSet<SiteListMaster> SiteListMasters { get; set; }
        public virtual DbSet<SupplierAccountDetail> SupplierAccountDetails { get; set; }
        public virtual DbSet<SupplierBlanketPODetail> SupplierBlanketPODetails { get; set; }
        public virtual DbSet<SupplierBlanketPOMaster> SupplierBlanketPOMasters { get; set; }
        public virtual DbSet<SupplierCatalog> SupplierCatalogs { get; set; }
        public virtual DbSet<SupplierCatalogTracker> SupplierCatalogTrackers { get; set; }
        public virtual DbSet<SupplierMaster> SupplierMasters { get; set; }
        public virtual DbSet<TechnicianMaster> TechnicianMasters { get; set; }
        public virtual DbSet<ToolAssetCount> ToolAssetCounts { get; set; }
        public virtual DbSet<ToolAssetCountDetail> ToolAssetCountDetails { get; set; }
        public virtual DbSet<ToolAssetCountLineItemDetail> ToolAssetCountLineItemDetails { get; set; }
        public virtual DbSet<ToolAssetMoveMaterialDetail> ToolAssetMoveMaterialDetails { get; set; }
        public virtual DbSet<ToolAssetMoveMaterialMaster> ToolAssetMoveMaterialMasters { get; set; }
        public virtual DbSet<ToolAssetOrderDetail> ToolAssetOrderDetails { get; set; }
        public virtual DbSet<ToolAssetOrderMaster> ToolAssetOrderMasters { get; set; }
        public virtual DbSet<ToolAssetPullDetail> ToolAssetPullDetails { get; set; }
        public virtual DbSet<ToolAssetPullMaster> ToolAssetPullMasters { get; set; }
        public virtual DbSet<ToolAssetQuantityDetail> ToolAssetQuantityDetails { get; set; }
        public virtual DbSet<ToolCategoryMaster> ToolCategoryMasters { get; set; }
        public virtual DbSet<ToolCheckInHistory> ToolCheckInHistories { get; set; }
        public virtual DbSet<ToolCheckInOutHistory> ToolCheckInOutHistories { get; set; }
        public virtual DbSet<ToolDetail> ToolDetails { get; set; }
        public virtual DbSet<ToolImageDetail> ToolImageDetails { get; set; }
        public virtual DbSet<ToolLocationDetail> ToolLocationDetails { get; set; }
        public virtual DbSet<ToolMaintenanceDetail> ToolMaintenanceDetails { get; set; }
        public virtual DbSet<ToolMaster> ToolMasters { get; set; }
        public virtual DbSet<ToolMoveInOutDetail> ToolMoveInOutDetails { get; set; }
        public virtual DbSet<ToolsMaintenance> ToolsMaintenances { get; set; }
        public virtual DbSet<ToolsMaintenanceDate> ToolsMaintenanceDates { get; set; }
        public virtual DbSet<ToolsOdometer> ToolsOdometers { get; set; }
        public virtual DbSet<ToolsScheduler> ToolsSchedulers { get; set; }
        public virtual DbSet<ToolsSchedulerDetail> ToolsSchedulerDetails { get; set; }
        public virtual DbSet<ToolsSchedulerMapping> ToolsSchedulerMappings { get; set; }
        public virtual DbSet<ToolWrittenOff> ToolWrittenOffs { get; set; }
        public virtual DbSet<ToolWrittenOffCategory> ToolWrittenOffCategories { get; set; }
        public virtual DbSet<TransferDetail> TransferDetails { get; set; }
        public virtual DbSet<TransferInOutItemDetail> TransferInOutItemDetails { get; set; }
        public virtual DbSet<TransferInOutQtyDetail> TransferInOutQtyDetails { get; set; }
        public virtual DbSet<TransferMaster> TransferMasters { get; set; }
        public virtual DbSet<UDF> UDFs { get; set; }
        public virtual DbSet<UDFModule> UDFModules { get; set; }
        public virtual DbSet<UDFOption> UDFOptions { get; set; }
        public virtual DbSet<UnitMaster> UnitMasters { get; set; }
        public virtual DbSet<UserMaster> UserMasters { get; set; }
        public virtual DbSet<UserRoleDetail> UserRoleDetails { get; set; }
        public virtual DbSet<UserRoomAccess> UserRoomAccesses { get; set; }
        public virtual DbSet<UserRoomsDetail> UserRoomsDetails { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<UsersUISetting> UsersUISettings { get; set; }
        public virtual DbSet<UserSupplierFilter> UserSupplierFilters { get; set; }
        public virtual DbSet<UserTypeMaster> UserTypeMasters { get; set; }
        public virtual DbSet<VenderMaster> VenderMasters { get; set; }
        public virtual DbSet<ViewReportHistory> ViewReportHistories { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkOrderImageDetail> WorkOrderImageDetails { get; set; }
        public virtual DbSet<WorkOrderLineItem> WorkOrderLineItems { get; set; }
        public virtual DbSet<eMailAttachment> eMailAttachments { get; set; }
        public virtual DbSet<MinMaxDashboardAuditTrail> MinMaxDashboardAuditTrails { get; set; }
        public virtual DbSet<ReceivedOrderTransferDetail> ReceivedOrderTransferDetails { get; set; }
        public virtual DbSet<ReportAlertConfig> ReportAlertConfigs { get; set; }
        public virtual DbSet<PullMaster> PullMasters { get; set; }
        public virtual DbSet<OrderMaster> OrderMasters { get; set; }
        public virtual DbSet<ReportMaster> ReportMasters { get; set; }
        public virtual DbSet<ItemMaster> ItemMasters { get; set; }
        public virtual DbSet<QuoteDetail> QuoteDetails { get; set; }
        public virtual DbSet<QuoteMaster> QuoteMasters { get; set; }
        public virtual DbSet<QuoteSupplierDetail> QuoteSupplierDetails { get; set; }
        public virtual DbSet<eVMISetup> eVMISetups { get; set; }
        public virtual DbSet<BinMaster> BinMasters { get; set; }
        public virtual DbSet<DashboardParameter> DashboardParameters { get; set; }
        public virtual DbSet<Room> Rooms { get; set; }
        public virtual DbSet<ItemLocationDetail> ItemLocationDetails { get; set; }
        public virtual DbSet<RequisitionMaster> RequisitionMasters { get; set; }
        public virtual DbSet<eMailToSend> eMailToSends { get; set; }
    }
}
