//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eVMISetup
    {
        public long ID { get; set; }
        public Nullable<int> PollType { get; set; }
        public Nullable<int> PollInterval { get; set; }
        public Nullable<System.TimeSpan> PollTime1 { get; set; }
        public Nullable<System.TimeSpan> PollTime2 { get; set; }
        public Nullable<System.TimeSpan> PollTime3 { get; set; }
        public Nullable<System.TimeSpan> PollTime4 { get; set; }
        public Nullable<System.TimeSpan> PollTime5 { get; set; }
        public Nullable<System.TimeSpan> PollTime6 { get; set; }
        public string ErrorEmailAddresses { get; set; }
        public bool IsSuggstedOrder { get; set; }
        public bool IsCriticalOrders { get; set; }
        public bool IsBadPolls { get; set; }
        public Nullable<System.TimeSpan> InactivityReportStart { get; set; }
        public Nullable<System.TimeSpan> InactivityReportEnd { get; set; }
        public bool InactivityonSaturday { get; set; }
        public bool InactivityonSunday { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<System.DateTime> NextPollDate { get; set; }
        public string CountType { get; set; }
        public Nullable<long> PollAllBetweenTime { get; set; }
        public Nullable<int> ShelfID { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public Nullable<long> RoomScheduleID { get; set; }
        public bool IsScheduleActive { get; set; }
    }
}
