//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class eVMIPollHistory
    {
        public long ID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public long BinID { get; set; }
        public Nullable<double> BegingCustOwnQty { get; set; }
        public Nullable<double> EndingCustOwnQty { get; set; }
        public Nullable<double> BegingConsQty { get; set; }
        public Nullable<double> EndingConsQty { get; set; }
        public Nullable<double> BeginingQty { get; set; }
        public Nullable<double> EndingQty { get; set; }
        public int PollType { get; set; }
        public System.DateTime PollDate { get; set; }
        public System.DateTime Created { get; set; }
        public long CreatedBy { get; set; }
        public System.Guid GUID { get; set; }
        public long RoomID { get; set; }
        public long CompanyID { get; set; }
        public Nullable<double> NewQuantity { get; set; }
        public Nullable<int> PollStatus { get; set; }
        public string PollStatusDesc { get; set; }
        public Nullable<System.DateTime> Historydate { get; set; }
    }
}
