//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FTPMaster
    {
        public long ID { get; set; }
        public string SFtpName { get; set; }
        public string ServerAddress { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Port { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public Nullable<long> EnterpriseID { get; set; }
        public Nullable<long> UserID { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public bool IsImportFTP { get; set; }
        public string ContactEmail { get; set; }
    }
}
