//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryAnalysisMonthWise
    {
        public long ID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public int CalculationMonth { get; set; }
        public int CalculationYear { get; set; }
        public System.DateTime CalculationDate { get; set; }
        public double MonthizedTurns { get; set; }
        public double MonthizedAverageUsage { get; set; }
        public double MonthizedInventoryValue { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public byte CalculationFor { get; set; }
        public double MonthizedPullCost { get; set; }
        public double MonthizedPullQuantity { get; set; }
        public double MonthizedOrderQuantity { get; set; }
        public double MonthizedOnHandQuantity { get; set; }
        public double MonthizedPullValueTurns { get; set; }
        public double MonthizedPullTurns { get; set; }
        public double MonthizedOrderTurns { get; set; }
        public double MinimumQuantity { get; set; }
        public double MaximumQuantity { get; set; }
        public string ManufacturerNumber { get; set; }
        public string SupplierPartNo { get; set; }
        public string UPC { get; set; }
        public Nullable<double> DefaultReorderQuantity { get; set; }
        public Nullable<double> DefaultPullQuantity { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Markup { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<double> ExtendedCost { get; set; }
        public Nullable<bool> Trend { get; set; }
        public Nullable<bool> Taxable { get; set; }
        public Nullable<bool> Consignment { get; set; }
        public Nullable<double> StagedQuantity { get; set; }
        public Nullable<double> InTransitquantity { get; set; }
        public Nullable<double> OnOrderQuantity { get; set; }
        public Nullable<double> OnTransferQuantity { get; set; }
        public Nullable<double> SuggestedOrderQuantity { get; set; }
        public Nullable<double> RequisitionedQuantity { get; set; }
        public Nullable<double> AverageUsage { get; set; }
        public Nullable<double> Turns { get; set; }
        public Nullable<double> OnHandQuantity { get; set; }
        public Nullable<double> CriticalQuantity { get; set; }
        public Nullable<double> WeightPerPiece { get; set; }
        public string ItemUniqueNumber { get; set; }
        public Nullable<bool> IsTransfer { get; set; }
        public Nullable<bool> IsPurchase { get; set; }
        public Nullable<long> DefaultLocation { get; set; }
        public Nullable<int> InventoryClassification { get; set; }
        public Nullable<bool> SerialNumberTracking { get; set; }
        public Nullable<bool> LotNumberTracking { get; set; }
        public Nullable<bool> DateCodeTracking { get; set; }
        public Nullable<int> ItemType { get; set; }
        public string IsLotSerialExpiryCost { get; set; }
        public Nullable<bool> IsItemLevelMinMaxQtyRequired { get; set; }
        public Nullable<bool> IsEnforceDefaultReorderQuantity { get; set; }
        public Nullable<double> AverageCost { get; set; }
        public Nullable<bool> IsBuildBreak { get; set; }
        public string BondedInventory { get; set; }
        public Nullable<double> OnReturnQuantity { get; set; }
        public Nullable<byte> TrendingSetting { get; set; }
        public Nullable<bool> PullQtyScanOverride { get; set; }
        public Nullable<bool> IsAutoInventoryClassification { get; set; }
        public Nullable<bool> IsPackslipMandatoryAtReceive { get; set; }
        public Nullable<double> SuggestedTransferQuantity { get; set; }
        public Nullable<double> QtyToMeetDemand { get; set; }
        public double MonthizedPullValueAverageUsage { get; set; }
        public double MonthizedPullAverageUsage { get; set; }
        public double MonthizedOrderAverageUsage { get; set; }
        public double AnnualizedPullValueAverageUsage { get; set; }
        public double AnnualizedPullAverageUsage { get; set; }
        public double AnnualizedOrderAverageUsage { get; set; }
        public double AnnualizedPullValueTurns { get; set; }
        public double AnnualizedPullTurns { get; set; }
        public double AnnualizedOrderTurns { get; set; }
    }
}
