//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCountCycle
    {
        public long ID { get; set; }
        public long CycleCountSettingId { get; set; }
        public int InventoryClasification { get; set; }
        public int CycleNumber { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int OneCycleAvailedDays { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
    }
}
