//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCount
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string CountName { get; set; }
        public string CountItemDescription { get; set; }
        public string CountType { get; set; }
        public string CountStatus { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public short Year { get; set; }
        public long CompanyId { get; set; }
        public long RoomId { get; set; }
        public System.DateTime CountDate { get; set; }
        public Nullable<System.DateTime> CountCompletionDate { get; set; }
        public Nullable<bool> IsAutomatedCompletion { get; set; }
        public Nullable<System.Guid> CompleteCauseCountGUID { get; set; }
        public bool IsApplied { get; set; }
        public bool IsClosed { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<System.Guid> ProjectSpendGUID { get; set; }
        public string ReleaseNumber { get; set; }
        public bool IsCycleCount { get; set; }
        public System.String PullOrderNumber { get; set; }
    }
}
