//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryCountDetail_History
    {
        public long HistoryID { get; set; }
        public string Action { get; set; }
        public Nullable<long> ICHistoryId { get; set; }
        public long ID { get; set; }
        public System.Guid InventoryCountGUID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public System.Guid BinGUID { get; set; }
        public double CountConsignedQuantity { get; set; }
        public double CountCustOwnedQuantity { get; set; }
        public double ItemConsignedQuantity { get; set; }
        public double ItemCustOwnedQuantity { get; set; }
        public string CountLineItemDescription { get; set; }
        public string CountItemStatus { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public System.Guid GUID { get; set; }
        public double ItemQuantity { get; set; }
        public double CountQuantity { get; set; }
        public long BinID { get; set; }
        public bool IsApplied { get; set; }
        public bool IsStagingLocationCount { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public double CusOwnedDifference { get; set; }
        public double ConsignedDifference { get; set; }
        public Nullable<int> InventoryClassification { get; set; }
        public string WhatWhereAction { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<System.DateTime> HistoryDate { get; set; }
        public Nullable<System.Guid> ProjectSpendGUID { get; set; }
        public Nullable<double> CusOwnedDifferenceCost { get; set; }
        public Nullable<double> ConsignedDifferenceCost { get; set; }
        public Nullable<double> CusOwnedDifferencePrice { get; set; }
        public Nullable<double> ConsignedDifferencePrice { get; set; }
        public Nullable<System.Guid> SupplierAccountGuid { get; set; }
        public string PullOrderNumber { get; set; }
    }
}
