//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLocationeVMISetup
    {
        public long ID { get; set; }
        public Nullable<long> BinID { get; set; }
        public string eVMISensorPort { get; set; }
        public Nullable<double> eVMISensorID { get; set; }
        public Nullable<double> PoundsPerPiece { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> CustomerOwnedQuantity { get; set; }
        public Nullable<double> ConsignedQuantity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    
        public virtual BinMaster BinMaster { get; set; }
    }
}
