//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemStockOutMailLog
    {
        public long ItemId { get; set; }
        public string ItemNumber { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public double OnHandQuantity { get; set; }
        public long Id { get; set; }
        public long BinID { get; set; }
    }
}
