//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemSupplierDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public long SupplierID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string SupplierName { get; set; }
        public string SupplierNumber { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> BlanketPOID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual SupplierBlanketPODetail SupplierBlanketPODetail { get; set; }
        public virtual SupplierMaster SupplierMaster { get; set; }
        public virtual Room Room1 { get; set; }
        public virtual Room Room2 { get; set; }
    }
}
