//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitMaster
    {
        public long ID { get; set; }
        public string KitPartNumber { get; set; }
        public string Description { get; set; }
        public Nullable<bool> ReOrderType { get; set; }
        public Nullable<int> KitCategory { get; set; }
        public Nullable<double> AvailableKitQuentity { get; set; }
        public Nullable<double> AvailableWIPKit { get; set; }
        public Nullable<double> KitDemand { get; set; }
        public Nullable<double> KitCost { get; set; }
        public Nullable<double> KitSellPrice { get; set; }
        public Nullable<double> MinimumKitQuentity { get; set; }
        public Nullable<double> MaximumKitQuentity { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public long CompanyID { get; set; }
        public long Room { get; set; }
        public Nullable<bool> IsNotification { get; set; }
        public Nullable<double> CriticalQuantity { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
