//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelTemplateMaster
    {
        public long TemplateID { get; set; }
        public string TemplateName { get; set; }
        public string LabelSize { get; set; }
        public int NoOfLabelPerSheet { get; set; }
        public int NoOfColumns { get; set; }
        public double PageWidth { get; set; }
        public double PageHeight { get; set; }
        public double LabelWidth { get; set; }
        public double LabelHeight { get; set; }
        public double PageMarginLeft { get; set; }
        public double PageMarginRight { get; set; }
        public double PageMarginTop { get; set; }
        public double PageMarginBottom { get; set; }
        public double LabelSpacingHorizontal { get; set; }
        public double LabelSpacingVerticle { get; set; }
        public double LabelPaddingLeft { get; set; }
        public double LabelPaddingRight { get; set; }
        public double LabelPaddingTop { get; set; }
        public double LabelPaddingBottom { get; set; }
        public int LabelType { get; set; }
        public long ID { get; set; }
        public Nullable<long> CompanyID { get; set; }
    }
}
