//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelModuleTemplateDetail
    {
        public long ID { get; set; }
        public long ModuleID { get; set; }
        public long TemplateDetailID { get; set; }
        public long CompanyID { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public Nullable<long> RoomID { get; set; }
    
        public virtual LabelFieldModuleTemplateDetail LabelFieldModuleTemplateDetail { get; set; }
        public virtual LabelModuleMaster LabelModuleMaster { get; set; }
    }
}
