//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabelModuleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabelModuleMaster()
        {
            this.LabelFieldModuleTemplateDetails = new HashSet<LabelFieldModuleTemplateDetail>();
            this.LabelModuleFieldMasters = new HashSet<LabelModuleFieldMaster>();
            this.LabelModuleTemplateDetails = new HashSet<LabelModuleTemplateDetail>();
        }
    
        public long ID { get; set; }
        public string ModuleName { get; set; }
        public string ModuleDTOName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelFieldModuleTemplateDetail> LabelFieldModuleTemplateDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelModuleFieldMaster> LabelModuleFieldMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabelModuleTemplateDetail> LabelModuleTemplateDetails { get; set; }
    }
}
