//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MaterialStagingPullDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> MaterialStagingGUID { get; set; }
        public Nullable<System.Guid> MaterialStagingdtlGUID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> CustomerOwnedQuantity { get; set; }
        public Nullable<double> ConsignedQuantity { get; set; }
        public Nullable<double> PoolQuantity { get; set; }
        public string SerialNumber { get; set; }
        public string LotNumber { get; set; }
        public string Expiration { get; set; }
        public string Received { get; set; }
        public Nullable<long> BinID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public string PullCredit { get; set; }
        public Nullable<System.Guid> ItemLocationDetailGUID { get; set; }
        public long StagingBinId { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> OrderDetailGUID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public bool IsConsignedSerialLot { get; set; }
        public Nullable<double> InitialQuantityWeb { get; set; }
        public Nullable<double> InitialQuantityPDA { get; set; }
    
        public virtual BinMaster BinMaster { get; set; }
        public virtual BinMaster BinMaster1 { get; set; }
    }
}
