//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MinMaxDashboardAuditTrail
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public long CompanyID { get; set; }
        public long RoomID { get; set; }
        public Nullable<System.Guid> ItemGuid { get; set; }
        public Nullable<long> BinID { get; set; }
        public string Action { get; set; }
        public System.DateTime ActionDate { get; set; }
        public long UserID { get; set; }
    }
}
