//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleNotification
    {
        public long pk_Notification { get; set; }
        public long ModuleId { get; set; }
        public long UserId { get; set; }
        public long RoomId { get; set; }
        public int Notification { get; set; }
    }
}
