//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ModuleMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ModuleMaster()
        {
            this.PermissionTemplateDetails = new HashSet<PermissionTemplateDetail>();
        }
    
        public long ID { get; set; }
        public string ModuleName { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string Value { get; set; }
        public Nullable<int> Priority { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<bool> IsModule { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<int> GroupID { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> DisplayOrderNumber { get; set; }
        public string ResourceKey { get; set; }
        public string ToolTipResourceKey { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionTemplateDetail> PermissionTemplateDetails { get; set; }
    }
}
