//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoveMaterialDetail
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid MoveMaterialGuid { get; set; }
        public double CustomerQty { get; set; }
        public double ConsignQty { get; set; }
        public double TotalQuanity { get; set; }
        public string SerialNumber { get; set; }
        public string LotNumber { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public long RoomID { get; set; }
        public long CompanyID { get; set; }
        public System.Guid ItemLocationDetailsGUID_Source { get; set; }
        public System.Guid ItemLocationDetailsGUID_Destination { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    }
}
