//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public long ID { get; set; }
        public long RoomScheduleID { get; set; }
        public string SupplierIds { get; set; }
        public string EmailAddress { get; set; }
        public string AttachmentTypes { get; set; }
        public string AttachmentReportIDs { get; set; }
        public Nullable<long> EmailTemplateID { get; set; }
        public Nullable<long> ReportID { get; set; }
        public System.DateTime Created { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public long UpdatedBy { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public int ScheduleFor { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsActive { get; set; }
        public Nullable<short> ReportDataSelectionType { get; set; }
        public Nullable<long> ReportDataSince { get; set; }
        public Nullable<System.DateTime> ScheduleRunTime { get; set; }
        public Nullable<long> FTPId { get; set; }
        public int NotificationMode { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<bool> SendEmptyEmail { get; set; }
        public bool HideHeader { get; set; }
        public bool ShowSignature { get; set; }
        public string SortSequence { get; set; }
        public string XMLValue { get; set; }
        public string RoomIDs { get; set; }
        public string CompanyIDs { get; set; }
        public string Range { get; set; }
        public string Status { get; set; }
    }
}
