//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> OrderGUID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<long> Bin { get; set; }
        public Nullable<double> RequestedQuantity { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<double> ReceivedQuantity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public System.Guid GUID { get; set; }
        public string ASNNumber { get; set; }
        public Nullable<double> ApprovedQuantity { get; set; }
        public Nullable<bool> IsEDIRequired { get; set; }
        public Nullable<bool> IsEDISent { get; set; }
        public Nullable<System.DateTime> LastEDIDate { get; set; }
        public Nullable<double> InTransitQuantity { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<bool> IsCloseItem { get; set; }
        public string LineNumber { get; set; }
        public string ControlNumber { get; set; }
        public string Comment { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<double> OrderLineItemExtendedCost { get; set; }
        public Nullable<double> OrderLineItemExtendedPrice { get; set; }
        public Nullable<double> RequestedQuantityUOM { get; set; }
        public Nullable<double> ApprovedQuantityUOM { get; set; }
        public Nullable<double> ReceivedQuantityUOM { get; set; }
        public Nullable<double> InTransitQuantityUOM { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string SupplierPartNo { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> ItemCostUOM { get; set; }
        public Nullable<int> ItemCostUOMValue { get; set; }
        public Nullable<double> ItemMarkup { get; set; }
        public Nullable<double> ItemSellPrice { get; set; }
    }
}
