//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDAEmailsToSend
    {
        public System.Guid GUID { get; set; }
        public long CompanyId { get; set; }
        public long RoomId { get; set; }
        public System.Guid RecordGUID { get; set; }
        public string RecordFromTable { get; set; }
        public string EmailTemplateType { get; set; }
        public bool IsSent { get; set; }
        public long CreatedByUserId { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
