//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PDAGridColumnList
    {
        public long ID { get; set; }
        public string ListName { get; set; }
        public string TableName { get; set; }
        public string GridColumnName { get; set; }
        public string GridColumnValue { get; set; }
        public bool IsFixedColumn { get; set; }
        public short FixedColumnOrder { get; set; }
        public bool IsActive { get; set; }
        public string GridColumnValueWithoutAlias { get; set; }
        public Nullable<bool> IsSearchFixed { get; set; }
        public string GridColumnAlias { get; set; }
    }
}
