//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PullMaster
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ProjectSpendGUID { get; set; }
        public string UOI { get; set; }
        public Nullable<double> CustomerOwnedQuantity { get; set; }
        public Nullable<double> ConsignedQuantity { get; set; }
        public Nullable<double> PoolQuantity { get; set; }
        public Nullable<double> PULLCost { get; set; }
        public Nullable<double> CreditCustomerOwnedQuantity { get; set; }
        public Nullable<double> CreditConsignedQuantity { get; set; }
        public Nullable<long> BinID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public string ActionType { get; set; }
        public string PullCredit { get; set; }
        public Nullable<System.Guid> RequisitionDetailGUID { get; set; }
        public Nullable<bool> Billing { get; set; }
        public Nullable<System.Guid> WorkOrderDetailGUID { get; set; }
        public Nullable<System.Guid> CountLineItemGuid { get; set; }
        public Nullable<bool> IsEDIRequired { get; set; }
        public Nullable<bool> IsEDISent { get; set; }
        public Nullable<System.DateTime> LastEDIDate { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<double> ItemOnhandQty { get; set; }
        public bool IsAddedFromPDA { get; set; }
        public bool IsProcessedAfterSync { get; set; }
        public Nullable<double> ItemStageQty { get; set; }
        public Nullable<double> ItemLocationOnhandQty { get; set; }
        public Nullable<double> ItemStageLocationQty { get; set; }
        public string PullOrderNumber { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<double> PullPrice { get; set; }
        public Nullable<System.Guid> SupplierAccountGuid { get; set; }
        public Nullable<double> ItemAverageCost { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<int> ItemCostUOMValue { get; set; }
        public Nullable<double> ItemMarkup { get; set; }
        public Nullable<double> ItemSellPrice { get; set; }
        public long PullType { get; set; }
        public bool IsCustomerEDISent { get; set; }
    
        public virtual BinMaster BinMaster { get; set; }
        public virtual CompanyMaster CompanyMaster { get; set; }
    }
}
