//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PullDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> PULLGUID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<System.Guid> ProjectSpendGUID { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> CustomerOwnedQuantity { get; set; }
        public Nullable<double> ConsignedQuantity { get; set; }
        public Nullable<double> PoolQuantity { get; set; }
        public string SerialNumber { get; set; }
        public string LotNumber { get; set; }
        public string Expiration { get; set; }
        public string Received { get; set; }
        public Nullable<long> BinID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public string PullCredit { get; set; }
        public Nullable<System.Guid> ItemLocationDetailGUID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> MaterialStagingPullDetailGUID { get; set; }
        public Nullable<double> ItemOnhandQty { get; set; }
        public bool IsAddedFromPDA { get; set; }
        public bool IsProcessedAfterSync { get; set; }
        public Nullable<double> ItemStageQty { get; set; }
        public Nullable<double> ItemLocationOnhandQty { get; set; }
        public Nullable<double> ItemStageLocationQty { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<double> CreditCustomerOwnedQuantity { get; set; }
        public Nullable<double> CreditConsignedQuantity { get; set; }
        public Nullable<double> ItemPrice { get; set; }
    
        public virtual BinMaster BinMaster { get; set; }
    }
}
