//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteMaster
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string QuoteNumber { get; set; }
        public int QuoteStatus { get; set; }
        public string ReleaseNumber { get; set; }
        public Nullable<int> NoOfLineItems { get; set; }
        public string Comment { get; set; }
        public Nullable<long> RequesterID { get; set; }
        public Nullable<long> ApproverID { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public Nullable<System.DateTime> QuoteDate { get; set; }
        public Nullable<double> QuoteCost { get; set; }
        public Nullable<double> QuotePrice { get; set; }
        public long Room { get; set; }
        public long CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsEDIQuote { get; set; }
        public string QuoteNumber_ForSorting { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<System.Guid> CustomerGUID { get; set; }
        public string PackSlipNumber { get; set; }
        public string ShippingTrackNumber { get; set; }
        public Nullable<long> ShipVia { get; set; }
        public string CustomerAddress { get; set; }
        public Nullable<long> Supplier { get; set; }
        public Nullable<long> ChangeQuoteRevisionNo { get; set; }
        public Nullable<long> ShippingVendor { get; set; }
        public string AccountNumber { get; set; }
        public string RejectionReason { get; set; }
        public Nullable<System.Guid> SupplierAccountGuid { get; set; }
    }
}
