//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuoteDetail
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public System.Guid QuoteGUID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public Nullable<long> BinID { get; set; }
        public Nullable<double> RequestedQuantity { get; set; }
        public Nullable<double> ApprovedQuantity { get; set; }
        public Nullable<double> OrderedQuantity { get; set; }
        public Nullable<double> InTransitQuantity { get; set; }
        public Nullable<double> QuoteLineItemExtendedCost { get; set; }
        public Nullable<double> QuoteLineItemExtendedPrice { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public long Room { get; set; }
        public long CompanyID { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public string ASNNumber { get; set; }
        public Nullable<bool> IsEDIRequired { get; set; }
        public Nullable<bool> IsEDISent { get; set; }
        public Nullable<System.DateTime> LastEDIDate { get; set; }
        public Nullable<bool> IsCloseItem { get; set; }
        public string LineNumber { get; set; }
        public string ControlNumber { get; set; }
        public string Comment { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<double> RequestedQuantityUOM { get; set; }
        public Nullable<double> ApprovedQuantityUOM { get; set; }
        public Nullable<double> OrderedQuantityUOM { get; set; }
        public Nullable<double> InTransitQuantityUOM { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> ItemCostUOM { get; set; }
        public Nullable<long> SupplierID { get; set; }
        public string SupplierPartNo { get; set; }
        public Nullable<int> ItemCostUOMValue { get; set; }
        public Nullable<double> ItemMarkup { get; set; }
        public Nullable<double> ItemSellPrice { get; set; }
        public bool IsOrdered { get; set; }
    }
}
