//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegionalSetting
    {
        public long ID { get; set; }
        public long EnterpriseId { get; set; }
        public long CompanyId { get; set; }
        public long RoomId { get; set; }
        public long UserId { get; set; }
        public string CultureCode { get; set; }
        public string ShortDatePattern { get; set; }
        public string LongDatePattern { get; set; }
        public string ShortTimePattern { get; set; }
        public string LongTimePattern { get; set; }
        public int NumberDecimalDigits { get; set; }
        public int CurrencyDecimalDigits { get; set; }
        public string NumberDecimalSeparator { get; set; }
        public string CurrencyGroupSeparator { get; set; }
        public string TimeZoneName { get; set; }
        public int TimeZoneOffSet { get; set; }
        public string CurrencySymbol { get; set; }
        public Nullable<int> GridRefreshTimeInSecond { get; set; }
        public Nullable<double> WeightDecimalPoints { get; set; }
        public Nullable<int> TurnsAvgDecimalPoints { get; set; }
        public Nullable<int> NumberOfBackDaysToSyncOverPDA { get; set; }
        public bool TZSupportDayLight { get; set; }
        public Nullable<System.DateTime> DayLightStartTime { get; set; }
        public Nullable<System.DateTime> DayLightEndTime { get; set; }
        public long Numberofentriestoloadattime { get; set; }
        public long Numberofinitialentryatatime { get; set; }
    }
}
