//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportAlertConfig
    {
        public long ID { get; set; }
        public Nullable<long> ReportID { get; set; }
        public Nullable<long> EmailTemplateID { get; set; }
        public bool AllowScheduleIMM { get; set; }
        public bool AllowScheduleHourly { get; set; }
        public bool AllowScheduleWeekly { get; set; }
        public bool AllowScheduleMonthly { get; set; }
        public string AllowedIMMActions { get; set; }
        public bool AllowDataSelectSinceLastReportFilter { get; set; }
        public bool AllowDataSinceFilter { get; set; }
        public bool AllowSupplierFilter { get; set; }
        public bool AllowPDFAttachment { get; set; }
        public bool AllowExcelAttachment { get; set; }
        public bool AllowAttachmentSelection { get; set; }
        public string AllowedAttahmentReports { get; set; }
        public bool AllowScheduleDaily { get; set; }
        public bool AllowDataSelectFirstOfMonth { get; set; }
        public bool AllowRangeDataSelect { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> UpdatedBy { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsSupplierRequired { get; set; }
        public bool IsDateRangeRequired { get; set; }
    }
}
