//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMaster
    {
        public long ID { get; set; }
        public string ReportName { get; set; }
        public string ReportFileName { get; set; }
        public int ReportType { get; set; }
        public long CompanyID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public string SortColumns { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedON { get; set; }
        public string SubReportFileName { get; set; }
        public bool IsPrivate { get; set; }
        public Nullable<long> PrivateUserID { get; set; }
        public bool IsBaseReport { get; set; }
        public string MasterReportResFile { get; set; }
        public string SubReportResFile { get; set; }
        public bool IsIncludeDateRange { get; set; }
        public bool IsIncludeTotal { get; set; }
        public bool IsIncludeSubTotal { get; set; }
        public bool IsIncludeGrandTotal { get; set; }
        public bool IsIncludeGroup { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<long> ParentID { get; set; }
        public string ToEmailAddress { get; set; }
        public string ModuleName { get; set; }
        public Nullable<bool> ISEnterpriseReport { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> SetAsDefaultPrintReport { get; set; }
        public Nullable<bool> IsIncludeTax1 { get; set; }
        public Nullable<bool> IsIncludeTax2 { get; set; }
        public Nullable<bool> IsNotEditable { get; set; }
        public Nullable<bool> IsDefaultReport { get; set; }
        public Nullable<bool> HideHeader { get; set; }
        public Nullable<bool> ShowSignature { get; set; }
        public string ReportAppIntent { get; set; }
        public string ResourceKey { get; set; }
        public string CombineReportID { get; set; }
    }
}
