//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportMailLog
    {
        public long Id { get; set; }
        public long ReportID { get; set; }
        public long ScheduleID { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public string SendEmailAddress { get; set; }
        public long CompanyID { get; set; }
        public long RoomID { get; set; }
        public System.DateTime SendDate { get; set; }
        public long NotificationID { get; set; }
        public System.DateTime Created { get; set; }
    }
}
