//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionMaster
    {
        public long ID { get; set; }
        public string RequisitionNumber { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> WorkorderGUID { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<int> NumberofItemsrequisitioned { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public Nullable<System.Guid> ProjectSpendGUID { get; set; }
        public string RequisitionStatus { get; set; }
        public string RequisitionType { get; set; }
        public Nullable<long> BillingAccountID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsNotification { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<System.Guid> CustomerGUID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string RequisitionApprover { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<System.Guid> SupplierAccountGuid { get; set; }
        public string ReleaseNumber { get; set; }
        public Nullable<long> StagingID { get; set; }
        public Nullable<System.Guid> MaterialStagingGUID { get; set; }
        public double TotalSellPrice { get; set; }
        public Nullable<long> TechnicianID { get; set; }
        public Nullable<long> RequesterID { get; set; }
        public Nullable<long> ApproverID { get; set; }
        public string RequisitionDataLog { get; set; }
    
        public virtual SupplierAccountDetail SupplierAccountDetail { get; set; }
    }
}
