//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequisitionDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> RequisitionGUID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> QuantityRequisitioned { get; set; }
        public Nullable<double> QuantityPulled { get; set; }
        public Nullable<double> QuantityApproved { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public long Room { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public long CompanyID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> BinID { get; set; }
        public Nullable<System.Guid> ProjectSpendGUID { get; set; }
        public Nullable<bool> IsNotification { get; set; }
        public string PullUDF1 { get; set; }
        public string PullUDF2 { get; set; }
        public string PullUDF3 { get; set; }
        public string PullUDF4 { get; set; }
        public string PullUDF5 { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<bool> IsCloseItem { get; set; }
        public Nullable<System.Guid> QuickListItemGUID { get; set; }
        public Nullable<System.Guid> ToolGuid { get; set; }
        public string ToolCheckoutUDF1 { get; set; }
        public string ToolCheckoutUDF2 { get; set; }
        public string ToolCheckoutUDF3 { get; set; }
        public string ToolCheckoutUDF4 { get; set; }
        public string ToolCheckoutUDF5 { get; set; }
        public Nullable<System.Guid> TechnicianGuid { get; set; }
        public double ItemSellPrice { get; set; }
        public Nullable<System.Guid> SupplierAccountGuid { get; set; }
        public Nullable<long> ToolCategoryID { get; set; }
        public Nullable<bool> IsToolCategoryInsert { get; set; }
        public string PullOrderNumber { get; set; }
    
        public virtual BinMaster BinMaster { get; set; }
    }
}
