//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceFileLink
    {
        public int Id { get; set; }
        public string PageResourceFile { get; set; }
        public string ReportResourceFile { get; set; }
        public string PDAResourceFile { get; set; }
        public string Prefix { get; set; }
        public System.DateTime Created { get; set; }
    }
}
