//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResourceModuleDetail
    {
        public long ID { get; set; }
        public string FileName { get; set; }
        public string DisplayFileName { get; set; }
        public Nullable<long> ResourceModuleID { get; set; }
        public string ResModuleDetailsKey { get; set; }
    }
}
