//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleModuleDetail
    {
        public long ID { get; set; }
        public long RoleId { get; set; }
        public long RoomId { get; set; }
        public long ModuleID { get; set; }
        public bool IsInsert { get; set; }
        public bool IsDelete { get; set; }
        public bool IsUpdate { get; set; }
        public bool IsView { get; set; }
        public string ModuleValue { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public System.Guid GUID { get; set; }
        public bool ShowArchived { get; set; }
        public bool ShowUDF { get; set; }
        public bool ShowDeleted { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> EnterpriseID { get; set; }
        public bool ShowChangeLog { get; set; }
    }
}
