//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomSchedule
    {
        public long ScheduleID { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public short ScheduleMode { get; set; }
        public short DailyRecurringType { get; set; }
        public short DailyRecurringDays { get; set; }
        public short WeeklyRecurringWeeks { get; set; }
        public bool WeeklyOnMonday { get; set; }
        public bool WeeklyOnTuesday { get; set; }
        public bool WeeklyOnWednesday { get; set; }
        public bool WeeklyOnThursday { get; set; }
        public bool WeeklyOnFriday { get; set; }
        public bool WeeklyOnSaturday { get; set; }
        public bool WeeklyOnSunday { get; set; }
        public short MonthlyRecurringType { get; set; }
        public short MonthlyDateOfMonth { get; set; }
        public short MonthlyRecurringMonths { get; set; }
        public short MonthlyDayOfMonth { get; set; }
        public short SubmissionMethod { get; set; }
        public System.DateTime ScheduleRunTime { get; set; }
        public short ScheduleFor { get; set; }
        public Nullable<long> RoomId { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CompanyId { get; set; }
        public bool IsScheduleActive { get; set; }
        public Nullable<System.DateTime> NextRunDate { get; set; }
        public Nullable<System.Guid> AssetToolID { get; set; }
        public Nullable<long> ReportID { get; set; }
        public Nullable<short> ReportDataSelectionType { get; set; }
        public Nullable<long> ReportDataSince { get; set; }
        public Nullable<short> HourlyRecurringHours { get; set; }
        public Nullable<short> HourlyAtWhatMinute { get; set; }
        public Nullable<long> ScheduledBy { get; set; }
        public bool IsDeleted { get; set; }
        public string ScheduleName { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<long> UserID { get; set; }
    }
}
