//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScriptsExecution
    {
        public int ID { get; set; }
        public int UserId { get; set; }
        public string Script { get; set; }
        public string DatabaseName { get; set; }
        public Nullable<System.DateTime> CurrentDateTime { get; set; }
    }
}
