//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SiteListColumnDetail
    {
        public long ID { get; set; }
        public long ListId { get; set; }
        public string ColumnName { get; set; }
        public Nullable<int> OrderNumber { get; set; }
        public string ResourceFileName { get; set; }
        public string SortColumnName { get; set; }
        public bool IsVisibilityEditable { get; set; }
    }
}
