//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierCatalog
    {
        public long SupplierCatalogItemID { get; set; }
        public string ItemNumber { get; set; }
        public string Description { get; set; }
        public Nullable<double> SellPrice { get; set; }
        public Nullable<double> PackingQuantity { get; set; }
        public string ManufacturerPartNumber { get; set; }
        public string ImagePath { get; set; }
        public string UPC { get; set; }
        public string SupplierPartNumber { get; set; }
        public string SupplierName { get; set; }
        public string ManufacturerName { get; set; }
        public string ConcatedColumnText { get; set; }
        public string UOM { get; set; }
        public string CostUOM { get; set; }
        public Nullable<double> Cost { get; set; }
        public string UNSPSC { get; set; }
        public string Category { get; set; }
        public string LongDescription { get; set; }
    }
}
