//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupplierMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupplierMaster()
        {
            this.ItemSupplierDetails = new HashSet<ItemSupplierDetail>();
            this.SupplierAccountDetails = new HashSet<SupplierAccountDetail>();
            this.SupplierBlanketPODetails = new HashSet<SupplierBlanketPODetail>();
            this.Rooms = new HashSet<Room>();
        }
    
        public long ID { get; set; }
        public string SupplierName { get; set; }
        public string Description { get; set; }
        public string ReceiverID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string Contact { get; set; }
        public string Phone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public bool IsEmailPOInBody { get; set; }
        public bool IsEmailPOInPDF { get; set; }
        public bool IsEmailPOInCSV { get; set; }
        public bool IsEmailPOInX12 { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public System.Guid GUID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string SupplierColor { get; set; }
        public string BranchNumber { get; set; }
        public Nullable<decimal> MaximumOrderSize { get; set; }
        public bool IsSendtoVendor { get; set; }
        public bool IsVendorReturnAsn { get; set; }
        public bool IsSupplierReceivesKitComponents { get; set; }
        public Nullable<int> POAutoSequence { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<int> Days { get; set; }
        public string WeekDays { get; set; }
        public Nullable<int> MonthDays { get; set; }
        public Nullable<System.TimeSpan> ScheduleTime { get; set; }
        public Nullable<bool> IsAutoGenerate { get; set; }
        public Nullable<bool> IsAutoGenerateSubmit { get; set; }
        public string NextOrderNo { get; set; }
        public bool isForBOM { get; set; }
        public Nullable<long> RefBomId { get; set; }
        public Nullable<int> PullPurchaseNumberType { get; set; }
        public string LastPullPurchaseNumberUsed { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string SupplierImage { get; set; }
        public string ImageExternalURL { get; set; }
        public string ImageType { get; set; }
        public Nullable<int> DefaultOrderRequiredDays { get; set; }
        public string POAutoNrFixedValue { get; set; }
        public string PullPurchaseNrFixedValue { get; set; }
        public string AccountNo { get; set; }
        public bool IsOrderReleaseNumberEditable { get; set; }
        public string POAutoNrReleaseNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemSupplierDetail> ItemSupplierDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierAccountDetail> SupplierAccountDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SupplierBlanketPODetail> SupplierBlanketPODetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Room> Rooms { get; set; }
        public Nullable<int> QuoteAutoSequence { get; set; }
        public string NextQuoteNo { get; set; }
        public string QuoteAutoNrFixedValue { get; set; }
        public string QuoteAutoNrReleaseNumber { get; set; }

    }
}
