//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolsScheduler
    {
        public long ID { get; set; }
        public string SchedulerName { get; set; }
        public string ScheduleType { get; set; }
        public Nullable<double> OperationalHours { get; set; }
        public Nullable<double> Mileage { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<byte> ScheduleFor { get; set; }
        public string Description { get; set; }
        public int SchedulerType { get; set; }
        public int TimeBasedFrequency { get; set; }
        public int TimeBaseUnit { get; set; }
        public int RecurringDays { get; set; }
        public Nullable<int> CheckOuts { get; set; }
    }
}
