//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolAssetCountDetail
    {
        public long ID { get; set; }
        public System.Guid ToolAssetCountGUID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<System.Guid> ToolBinGUID { get; set; }
        public string CountLineItemDescription { get; set; }
        public string CountItemStatus { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public System.Guid GUID { get; set; }
        public double Quantity { get; set; }
        public double CountQuantity { get; set; }
        public long ToolBinID { get; set; }
        public bool IsApplied { get; set; }
        public Nullable<System.DateTime> AppliedDate { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public double QuantityDifference { get; set; }
        public string WhatWhereAction { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<double> DifferenceCost { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
    
        public virtual ToolLocationDetail ToolLocationDetail { get; set; }
    }
}
