//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolCheckInHistory
    {
        public long ID { get; set; }
        public Nullable<System.Guid> CheckInCheckOutGUID { get; set; }
        public string CheckOutStatus { get; set; }
        public Nullable<double> CheckedOutQTY { get; set; }
        public Nullable<double> CheckedOutMQTY { get; set; }
        public Nullable<System.DateTime> CheckOutDate { get; set; }
        public Nullable<System.DateTime> CheckInDate { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<double> CheckedOutQTYCurrent { get; set; }
        public Nullable<double> CheckedOutMQTYCurrent { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<System.Guid> TechnicianGuid { get; set; }
        public Nullable<System.DateTime> Historydate { get; set; }
        public Nullable<System.Guid> ToolDetailGUID { get; set; }
        public string SerialNumber { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
