//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolAssetOrderMaster
    {
        public long ID { get; set; }
        public string ToolAssetOrderNumber { get; set; }
        public string ReleaseNumber { get; set; }
        public string RejectionReason { get; set; }
        public string Comment { get; set; }
        public System.DateTime RequiredDate { get; set; }
        public int OrderStatus { get; set; }
        public string PackSlipNumber { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> RoomID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public System.Guid GUID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<int> OrderType { get; set; }
        public Nullable<double> OrderCost { get; set; }
        public Nullable<int> NoOfLineItems { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<long> ChangeOrderRevisionNo { get; set; }
        public string WhatWhereAction { get; set; }
        public string OrderNumber_ForSorting { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<bool> IsEDIOrder { get; set; }
        public string EditedOnAction { get; set; }
    }
}
