//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolMaster
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string ToolName { get; set; }
        public string Serial { get; set; }
        public string Description { get; set; }
        public Nullable<long> ToolCategoryID { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<bool> IscheckedOut { get; set; }
        public Nullable<int> IsGroupOfItems { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> CheckedOutQTY { get; set; }
        public Nullable<double> CheckedOutMQTY { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<byte> MaintenanceCount { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public bool IsAutoMaintain { get; set; }
        public Nullable<int> NoOfPastMntsToConsider { get; set; }
        public int MaintenanceType { get; set; }
        public Nullable<System.Guid> TechnicianGUID { get; set; }
        public string ToolImageExternalURL { get; set; }
        public string ImageType { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> SuggestedMaintenanceDate { get; set; }
        public Nullable<int> MaintenanceDueNoticeDays { get; set; }
        public Nullable<long> Type { get; set; }
        public bool IsBuildBreak { get; set; }
        public Nullable<double> AvailableToolQty { get; set; }
        public string ToolTypeTracking { get; set; }
        public bool SerialNumberTracking { get; set; }
        public bool LotNumberTracking { get; set; }
        public bool DateCodeTracking { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
