//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolsOdometer
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
        public Nullable<System.DateTime> EntryDate { get; set; }
        public Nullable<double> Odometer { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
