//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolAssetOrderDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ToolAssetOrderGUID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
        public Nullable<long> ToolBinID { get; set; }
        public Nullable<double> RequestedQuantity { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<double> ReceivedQuantity { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<double> ApprovedQuantity { get; set; }
        public Nullable<bool> IsEDIRequired { get; set; }
        public Nullable<bool> IsEDISent { get; set; }
        public Nullable<System.DateTime> LastEDIDate { get; set; }
        public Nullable<double> InTransitQuantity { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<bool> IsCloseTool { get; set; }
        public string LineNumber { get; set; }
        public string ControlNumber { get; set; }
        public string Comment { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
    }
}
