//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolMaintenanceDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> MaintenanceGUID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<double> ItemCost { get; set; }
        public Nullable<double> Quantity { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public long Room { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public long CompanyID { get; set; }
        public System.Guid GUID { get; set; }
    
        public virtual Room Room1 { get; set; }
    }
}
