//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolWrittenOff
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<long> ToolWrittenOffCategoryID { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string SerialNumber { get; set; }
        public bool IsUnWrittenOff { get; set; }
    }
}
