//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolLocationDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ToolLocationDetail()
        {
            this.ToolAssetCountDetails = new HashSet<ToolAssetCountDetail>();
        }
    
        public long ID { get; set; }
        public Nullable<System.Guid> ToolGuid { get; set; }
        public Nullable<System.Guid> LocationGuid { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchieved { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public Nullable<System.DateTime> LastUpdatedOn { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public Nullable<System.DateTime> ReceivedOnWeb { get; set; }
        public string WhatWhereAction { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<long> LocationID { get; set; }
        public Nullable<System.Guid> AssetGuid { get; set; }
        public Nullable<double> Quantity { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ToolAssetCountDetail> ToolAssetCountDetails { get; set; }
    }
}
