//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolMoveInOutDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> GUID { get; set; }
        public Nullable<System.Guid> ToolDetailGUID { get; set; }
        public Nullable<System.Guid> ToolItemGUID { get; set; }
        public string MoveInOut { get; set; }
        public Nullable<long> Quantity { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<System.DateTime> ReceivedOnWeb { get; set; }
        public Nullable<System.DateTime> ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string WhatWhereAction { get; set; }
        public string ReasonFromMove { get; set; }
        public Nullable<System.Guid> RefMoveInOutGUID { get; set; }
        public Nullable<double> MoveOutQuntity { get; set; }
    }
}
