//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolAssetCountLineItemDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<long> ToolBinID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> CountQuantity { get; set; }
        public string SerialNumber { get; set; }
        public string Comment { get; set; }
        public string Received { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public Nullable<double> Cost { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public Nullable<System.Guid> CountGUID { get; set; }
        public Nullable<System.Guid> CountDetailGUID { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<double> QuantityDifference { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
    }
}
