//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolAssetQuantityDetail
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
        public Nullable<long> ToolBinID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public long RoomID { get; set; }
        public long CompanyID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<System.DateTime> ReceivedDate { get; set; }
        public double InitialQuantityWeb { get; set; }
        public double InitialQuantityPDA { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public string EditedOnAction { get; set; }
        public long CreatedBy { get; set; }
        public long UpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public bool IsArchived { get; set; }
        public Nullable<double> Cost { get; set; }
        public string SerialNumber { get; set; }
        public Nullable<System.Guid> ToolAssetOrderDetailGUID { get; set; }
        public Nullable<System.Guid> PullGUID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string Description { get; set; }
    }
}
