//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ToolAssetPullMaster
    {
        public long ID { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> PULLCost { get; set; }
        public Nullable<long> ToolBinID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public Nullable<long> RoomID { get; set; }
        public string ActionType { get; set; }
        public Nullable<bool> IsEDIRequired { get; set; }
        public Nullable<bool> IsEDISent { get; set; }
        public Nullable<System.DateTime> LastEDIDate { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<double> ToolQuantity { get; set; }
        public Nullable<bool> IsAddedFromPDA { get; set; }
        public Nullable<bool> IsProcessedAfterSync { get; set; }
        public Nullable<double> ToolLocationQty { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<System.Guid> CountLineItemGuid { get; set; }
        public Nullable<System.Guid> ToolAssetCheckoutGUID { get; set; }
        public Nullable<System.Guid> ToolAssetCheckINGUID { get; set; }
        public Nullable<System.Guid> ToolAssetQuantityDetailGUID { get; set; }
        public string ReferalAction { get; set; }
    }
}
