//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferMaster
    {
        public long ID { get; set; }
        public string TransferNumber { get; set; }
        public System.DateTime RequireDate { get; set; }
        public long ReplenishingRoomID { get; set; }
        public long RequestingRoomID { get; set; }
        public string Comment { get; set; }
        public Nullable<long> StagingID { get; set; }
        public Nullable<int> TransferStatus { get; set; }
        public int RequestType { get; set; }
        public Nullable<System.Guid> RefTransferGUID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public System.Guid GUID { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public long CompanyID { get; set; }
        public long RoomID { get; set; }
        public string RejectionReason { get; set; }
        public string WhatWhereAction { get; set; }
        public Nullable<System.Guid> MaterialStagingGUID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public Nullable<int> NoOfItems { get; set; }
        public Nullable<double> TotalCost { get; set; }
        public Nullable<System.Guid> RefInOutTypeTransferGUID { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual Room Room { get; set; }
    }
}
