//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferInOutQtyDetail
    {
        public long ID { get; set; }
        public Nullable<System.Guid> TransferGUID { get; set; }
        public Nullable<System.Guid> TransferDetailGUID { get; set; }
        public Nullable<System.Guid> ItemGUID { get; set; }
        public Nullable<long> BinID { get; set; }
        public string TransferInOut { get; set; }
        public Nullable<double> CustomerOwnedQuantity { get; set; }
        public Nullable<double> ConsignedQuantity { get; set; }
        public double TotalQuantity { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public long Room { get; set; }
        public long CompanyID { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public System.Guid GUID { get; set; }
        public bool IsTransfered { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    
        public virtual BinMaster BinMaster { get; set; }
    }
}
