//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferDetail
    {
        public long ID { get; set; }
        public System.Guid TransferGUID { get; set; }
        public System.Guid ItemGUID { get; set; }
        public Nullable<long> Bin { get; set; }
        public double RequestedQuantity { get; set; }
        public Nullable<System.DateTime> RequiredDate { get; set; }
        public Nullable<double> ReceivedQuantity { get; set; }
        public Nullable<double> FulFillQuantity { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public long CreatedBy { get; set; }
        public long LastUpdatedBy { get; set; }
        public long Room { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public long CompanyID { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<double> IntransitQuantity { get; set; }
        public Nullable<double> ShippedQuantity { get; set; }
        public Nullable<bool> IsEDIRequired { get; set; }
        public Nullable<bool> IsEDISent { get; set; }
        public Nullable<System.DateTime> LastEDIDate { get; set; }
        public Nullable<double> ApprovedQuantity { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string ControlNumber { get; set; }
        public Nullable<long> DestinationBinId { get; set; }
    }
}
