//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDF
    {
        public long ID { get; set; }
        public long CompanyID { get; set; }
        public string UDFTableName { get; set; }
        public string UDFColumnName { get; set; }
        public string UDFControlType { get; set; }
        public string UDFOptionsCSV { get; set; }
        public string UDFDefaultValue { get; set; }
        public Nullable<bool> UDFIsRequired { get; set; }
        public Nullable<bool> UDFIsSearchable { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public System.Guid GUID { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsEncryption { get; set; }
        public Nullable<int> UDFMaxLength { get; set; }
    }
}
