//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UDFModule
    {
        public long ID { get; set; }
        public string UDFModuleName { get; set; }
        public string UDFModuleKeyName { get; set; }
        public int NoOfUdfs { get; set; }
        public System.Guid GUID { get; set; }
        public long CreatedBy { get; set; }
        public long UpdateBy { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
    }
}
