//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitMaster
    {
        public long ID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public string Unit { get; set; }
        public System.Guid GUID { get; set; }
        public string Description { get; set; }
        public string Odometer { get; set; }
        public Nullable<System.DateTime> OdometerUpdate { get; set; }
        public Nullable<decimal> OpHours { get; set; }
        public Nullable<System.DateTime> OpHoursUpdate { get; set; }
        public Nullable<long> SerialNo { get; set; }
        public Nullable<long> Year { get; set; }
        public string Make { get; set; }
        public string Model { get; set; }
        public string Plate { get; set; }
        public string EngineModel { get; set; }
        public string EngineSerialNo { get; set; }
        public Nullable<long> MarkupParts { get; set; }
        public Nullable<long> MarkupLabour { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public string UDF6 { get; set; }
        public string UDF7 { get; set; }
        public string UDF8 { get; set; }
        public string UDF9 { get; set; }
        public string UDF10 { get; set; }
        public bool isForBOM { get; set; }
        public Nullable<long> RefBomId { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    }
}
