//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersUISetting
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public string ListName { get; set; }
        public string JSONDATA { get; set; }
    }
}
