//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSupplierFilter
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public long UserId { get; set; }
        public long SuperAdminId { get; set; }
        public System.DateTime Created { get; set; }
        public Nullable<System.DateTime> LastUpdated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public long RoomId { get; set; }
        public long CompanyId { get; set; }
        public Nullable<long> EnterpriseId { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
    }
}
