//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eTurns.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        public long ID { get; set; }
        public System.Guid GUID { get; set; }
        public string WOName { get; set; }
        public Nullable<long> TechnicianID { get; set; }
        public string Technician { get; set; }
        public Nullable<long> CustomerID { get; set; }
        public string Customer { get; set; }
        public Nullable<System.Guid> AssetGUID { get; set; }
        public string Asset { get; set; }
        public Nullable<System.Guid> ToolGUID { get; set; }
        public string Tool { get; set; }
        public string WOStatus { get; set; }
        public Nullable<double> Odometer_OperationHours { get; set; }
        public Nullable<System.DateTime> Created { get; set; }
        public Nullable<System.DateTime> Updated { get; set; }
        public Nullable<long> CreatedBy { get; set; }
        public Nullable<long> LastUpdatedBy { get; set; }
        public Nullable<long> Room { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<bool> IsArchived { get; set; }
        public Nullable<long> CompanyID { get; set; }
        public string UDF1 { get; set; }
        public string UDF2 { get; set; }
        public string UDF3 { get; set; }
        public string UDF4 { get; set; }
        public string UDF5 { get; set; }
        public Nullable<int> UsedItems { get; set; }
        public Nullable<double> UsedItemsCost { get; set; }
        public string WOType { get; set; }
        public string WhatWhereAction { get; set; }
        public string SignatureName { get; set; }
        public bool IsSignatureCapture { get; set; }
        public bool IsSignatureRequired { get; set; }
        public string Description { get; set; }
        public Nullable<System.Guid> CustomerGUID { get; set; }
        public System.DateTime ReceivedOnWeb { get; set; }
        public System.DateTime ReceivedOn { get; set; }
        public string AddedFrom { get; set; }
        public string EditedFrom { get; set; }
        public string ReleaseNumber { get; set; }
        public Nullable<long> SupplierId { get; set; }
        public Nullable<System.Guid> SupplierAccountGuid { get; set; }
        public Nullable<int> CreatedFrom { get; set; }
        public double UsedItemsSellPrice { get; set; }
    
        public virtual CompanyMaster CompanyMaster { get; set; }
        public virtual TechnicianMaster TechnicianMaster { get; set; }
        public virtual Room Room1 { get; set; }
    }
}
